const KEY='bookbloom-books-v1';let books=JSON.parse(localStorage.getItem(KEY)||'[]');const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(books));render()}
function render(){const grid=$('#books'),empty=$('#empty');$('#count').textContent=`${books.length} book${books.length===1?'':'s'}`;$('#reviewBook').innerHTML='<option value="">Choose a captured book…</option>'+books.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join('');if(!books.length){grid.innerHTML='';empty.style.display='block';return}empty.style.display='none';grid.innerHTML=books.map(b=>`<article class="book-card"><img class="cover" src="${esc(b.cover)}" alt="Cover of ${esc(b.title)}" onerror="this.src='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22150%22 height=%22220%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22%231c1420%22/%3E%3Ctext x=%2250%25%22 y=%2250%25%22 fill=%22%23d8b36a%22 text-anchor=%22middle%22 font-size=%2216%22%3EBookBloom%3C/text%3E%3C/svg%3E'"><div class="book-info"><h3>${esc(b.title)}</h3><div class="author">${esc(b.author)}</div><div class="genre">${esc(b.genre)}</div>${b.rating?`<div class="stars">${'★'.repeat(b.rating)}${'☆'.repeat(5-b.rating)}</div>`:''}<button class="delete" data-delete="${b.id}">Remove from shelf</button><div class="review-card-actions"><button data-open-review="${b.id}">✒ Review</button><button data-share="${b.id}">↗ Share</button></div></div></article>`).join('')}
async function search(title){if(!title.trim())return;$('#status').textContent='Opening the archives…';$('#searchBtn').disabled=true;try{let data=null;const g=await fetch(`https://www.googleapis.com/books/v1/volumes?q=intitle:${encodeURIComponent(title)}&maxResults=1`).then(r=>r.json()).catch(()=>null);if(g?.items?.[0]){const v=g.items[0].volumeInfo;data={title:v.title,author:(v.authors||['Unknown author']).join(', '),genre:(v.categories||['Literature'])[0],cover:(v.imageLinks?.thumbnail||'').replace('http:','https://')}}if(!data){const o=await fetch(`https://openlibrary.org/search.json?title=${encodeURIComponent(title)}&limit=1`).then(r=>r.json()).catch(()=>null);if(o?.docs?.[0]){const d=o.docs[0];data={title:d.title,author:(d.author_name||['Unknown author']).slice(0,2).join(', '),genre:(d.subject||['Literature'])[0],cover:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-M.jpg`:''}}}if(!data)throw Error('not found');if(books.some(b=>b.title.toLowerCase()===data.title.toLowerCase())){$('#status').textContent='That book is already on your shelf.';return}books.unshift({id:crypto.randomUUID(),...data});save();$('#status').textContent=`Captured “${data.title}” into your library.`;location.hash='library'}catch(e){$('#status').textContent='The archives returned no matching book. Try another title.'}finally{$('#searchBtn').disabled=false}}
$('#searchBtn').onclick=()=>search($('#searchInput').value);$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search(e.target.value)});document.addEventListener('click',e=>{const d=e.target.closest('[data-delete]');if(d){books=books.filter(b=>b.id!==d.dataset.delete);save()}const demo=e.target.closest('[data-demo]');if(demo){$('#searchInput').value=demo.dataset.demo;search(demo.dataset.demo)}});$('#reviewForm').onsubmit=e=>{e.preventDefault();const b=books.find(x=>x.id===$('#reviewBook').value);if(!b)return;b.rating=Number($('#rating').value);b.review=$('#reviewText').value;save();e.target.reset();$('#status').textContent=`Your review of “${b.title}” has been sealed.`;location.hash='library'};render();

/* ===== BookBloom Luxury Gothic Experience ===== */
(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='enhancements.css';document.head.appendChild(css);
 const nav=document.createElement('div');nav.className='page-switch';nav.innerHTML='<button class="active" data-room="read-room">📚 Reading Room</button><button data-room="review-room">✒ Review Chamber</button><button data-room="tbr-room">☾ TBR Vault</button>';document.querySelector('main').prepend(nav);
 const read=document.querySelector('#library');read.classList.add('library-page');read.id='read-room';
 const review=document.querySelector('#review');review.classList.add('library-page');review.id='review-room';
 const tbr=document.createElement('section');tbr.id='tbr-room';tbr.className='library-page room-page room-tbr';tbr.innerHTML='<div class="room-inner"><p class="eyebrow">THE NEXT CHAPTER</p><h2>My TBR Vault</h2><p class="room-intro">Books waiting in the shadows. Add a title, capture its cover automatically, then move it from planned to started to finished.</p><div class="tbr-form"><input id="tbrInput" placeholder="Enter a book you want to read…"><button class="gold-btn" id="tbrAdd">＋ Add to TBR</button></div><div id="tbrList" class="tbr-list"></div></div>';
 document.querySelector('main').appendChild(tbr);
 const readRoom=document.createElement('div');readRoom.className='room-page room-read';readRoom.style.minHeight='0';readRoom.style.padding='0';readRoom.style.backgroundImage="url('https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=2200&q=90')";read.prepend(readRoom);
 const modal=document.createElement('div');modal.className='review-pop';modal.id='reviewPop';modal.innerHTML='<div class="review-dialog"><button class="close-pop" id="reviewClose">×</button><div class="review-head"><p class="eyebrow">BOOKBLOOM • FIRST REVIEW</p><h2 id="popTitle">Your first book review</h2></div><div class="review-body"><div class="review-book"><img id="popCover"><div><div class="author" id="popAuthor"></div><div class="review-stars" id="popStars"></div><div class="social-note">Write your review, then share it directly to your social platform.</div></div></div><textarea id="popReview" placeholder="What did this book make you feel, remember or question?"></textarea><div class="share-row"><button id="savePop">✒ Save Review</button><button id="shareWhats">WhatsApp</button><button id="shareFacebook">Facebook</button><button id="shareX">X</button><button id="shareLinkedIn">LinkedIn</button><button id="copyReview">Copy Review</button></div></div></div>';document.body.appendChild(modal);
 let activeBook=null,chosen=5;
 function starsHTML(r){return [1,2,3,4,5].map(i=>`<button data-rate="${i}" class="${i<=r?'on':''}">★</button>`).join('')}
 function openReview(id,first=false){activeBook=books.find(b=>b.id===id)||books[0];if(!activeBook)return;chosen=activeBook.rating||5;$('#popTitle').textContent=first?'Your First Book Review':activeBook.title;$('#popAuthor').textContent=activeBook.author||'Unknown author';$('#popCover').src=activeBook.cover||'';$('#popStars').innerHTML=starsHTML(chosen);$('#popReview').value=activeBook.review||'';modal.classList.add('show')}
 function closeReview(){modal.classList.remove('show')}
 document.addEventListener('click',e=>{const r=e.target.closest('[data-open-review]');if(r)openReview(r.dataset.openReview);const s=e.target.closest('[data-share]');if(s){openReview(s.dataset.share);setTimeout(()=>shareBook(books.find(b=>b.id===s.dataset.share)),0)} });
 $('#reviewClose').onclick=closeReview;modal.addEventListener('click',e=>{if(e.target===modal)closeReview()});
 $('#popStars').addEventListener('click',e=>{let b=e.target.closest('[data-rate]');if(!b)return;chosen=+b.dataset.rate;$('#popStars').innerHTML=starsHTML(chosen)});
 $('#savePop').onclick=()=>{if(!activeBook)return;activeBook.rating=chosen;activeBook.review=$('#popReview').value;save();$('#status').textContent=`Review saved for “${activeBook.title}”.`;closeReview()};
 function shareText(b){return `I rated “${b.title}” by ${b.author||'Unknown author'} ${b.rating||chosen}/5 ★ on BookBloom.\n\n${b.review||$('#popReview').value||'A book worth discovering.'}`}
 function shareBook(b){if(!b)return;const text=encodeURIComponent(shareText(b));const url=encodeURIComponent(location.href);window.open(`https://wa.me/?text=${text}%20${url}`,'_blank','noopener')}
 $('#shareWhats').onclick=()=>activeBook&&window.open(`https://wa.me/?text=${encodeURIComponent(shareText(activeBook)+' '+location.href)}`,'_blank','noopener');
 $('#shareFacebook').onclick=()=>activeBook&&window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(location.href)}&quote=${encodeURIComponent(shareText(activeBook))}`,'_blank','noopener');
 $('#shareX').onclick=()=>activeBook&&window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText(activeBook))}&url=${encodeURIComponent(location.href)}`,'_blank','noopener');
 $('#shareLinkedIn').onclick=()=>window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(location.href)}`,'_blank','noopener');
 $('#copyReview').onclick=async()=>{if(!activeBook)return;await navigator.clipboard?.writeText(shareText(activeBook));$('#status').textContent='Review copied — paste it anywhere you want to share.'};
 function tbrData(){return JSON.parse(localStorage.getItem('bookbloom-tbr-v1')||'[]')}
 function tbrSave(x){localStorage.setItem('bookbloom-tbr-v1',JSON.stringify(x));renderTBR()}
 function renderTBR(){let x=tbrData();$('#tbrList').innerHTML=x.length?x.map(b=>`<article class="tbr-item"><img src="${esc(b.cover||'')}" onerror="this.src='https://placehold.co/160x240/201524/f4d38b?text=BookBloom'"><div><h3>${esc(b.title)}</h3><div class="author">${esc(b.author||'Unknown author')}</div><div class="progress">${['planned','started','finished'].map(s=>`<button class="${b.status===s?'on':''}" data-tbr-status="${s}" data-tbr-id="${b.id}">${s[0].toUpperCase()+s.slice(1)}</button>`).join('')}</div><div style="margin-top:8px"><button class="delete" data-tbr-delete="${b.id}">Remove</button></div></div></article>`).join(''):'<p class="room-intro">Your vault is waiting for its next secret.</p>'}
 $('#tbrAdd').onclick=async()=>{let q=$('#tbrInput').value.trim();if(!q)return;let old=$('#status').textContent;$('#status').textContent='Capturing TBR cover…';let data=await lookupTBR(q);let x=tbrData();x.unshift({id:crypto.randomUUID(),title:data.title||q,author:data.author||'Unknown author',cover:data.cover||'',status:'planned'});tbrSave(x);$('#tbrInput').value='';$('#status').textContent=old||'TBR captured.'};
 async function lookupTBR(q){try{let g=await fetch(`https://www.googleapis.com/books/v1/volumes?q=intitle:${encodeURIComponent(q)}&maxResults=1`).then(r=>r.json());let v=g.items?.[0]?.volumeInfo;if(v)return{title:v.title,author:(v.authors||[]).join(', '),cover:(v.imageLinks?.large||v.imageLinks?.thumbnail||'').replace('http:','https:')}}catch(e){}try{let o=await fetch(`https://openlibrary.org/search.json?title=${encodeURIComponent(q)}&limit=1`).then(r=>r.json());let d=o.docs?.[0];return{title:d?.title||q,author:(d?.author_name||[]).slice(0,2).join(', '),cover:d?.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-L.jpg`:''}}catch(e){}return{title:q}}
 document.addEventListener('click',e=>{let s=e.target.closest('[data-tbr-status]');if(s){let x=tbrData(),b=x.find(v=>v.id===s.dataset.tbrId);if(b){b.status=s.dataset.tbrStatus;tbrSave(x)}}let d=e.target.closest('[data-tbr-delete]');if(d)tbrSave(tbrData().filter(v=>v.id!==d.dataset.tbrDelete));});
 nav.addEventListener('click',e=>{let b=e.target.closest('[data-room]');if(!b)return;nav.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.library-page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.room).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});
 // Convert the original review form into a review chamber shortcut and keep it functional.
 review.querySelector('.section-heading')?.insertAdjacentHTML('beforeend','<button class="gold-btn" id="firstReviewBtn" type="button">✒ Open First Review</button>');$('#firstReviewBtn').onclick=()=>books[0]&&openReview(books[0].id,true);
 renderTBR();
 // First-review popup requested: show it once when the library already contains a book.
 if(books.length&&!sessionStorage.getItem('bookbloom-first-review-shown')){sessionStorage.setItem('bookbloom-first-review-shown','1');setTimeout(()=>openReview(books[0].id,true),900)}
})();
